### ISSUE TITLE
Prefilled Name and Description

### ISSUE THREAD

**Issue by LightslicerGP** [TheAlienDoctor/minecraft-resource-pack-converter#10]
For either bedrock to java or vice versa, prefill the pack name and description before converting, to skip a step instead of needing to retype it if it it would match the original name and description

**Comment by TheAlienDoctor** [comment]
Added in [version 1.3.0](https://github.com/TheAlienDoctor/minecraft-resource-pack-converter/releases/tag/V1.3.0).
