### ISSUE TITLE
Support Title Screen Background conversion

### ISSUE THREAD

**Issue by LightslicerGP** [TheAlienDoctor/minecraft-resource-pack-converter#12]
From (at least) bedrock to java (I don't know if it already works for java to bedrock), when converting it should be able to convert the background in the title screen, since (I don't think, I mean it hasn't worked for me at least) it should be possible and hasn't been done already.

**Comment by TheAlienDoctor** [comment]
Hey there, an update will be releasing in the next couple of days. Most of it has already been committed to the repo if you want to compile it yourself, or run the uncompiled script. 
I must have missed them when I was going through everything I can convert.

- Alien

**Comment by TheAlienDoctor** [comment]
Added in [version 1.3.0](https://github.com/TheAlienDoctor/minecraft-resource-pack-converter/releases/tag/V1.3.0).
