### ISSUE TITLE
RTX/PBR Conversion Support

### ISSUE THREAD

**Issue by LightslicerGP** [TheAlienDoctor/minecraft-resource-pack-converter#15]
This could make the code very hefty and long, but it would be nice to convert an rtx pack from bedrock to a pack on java with the pbr textures as well, and to take a pbr texture pack from java to bedrock as an rtx pack

It could be time consuming, but it would be sick to have.

**Comment by TheAlienDoctor** [comment]
I seem to remember replying to this, but I can't see my reply so I'll do it again...

Adding PBR texture support isn't really something I see myself doing in the foreseeable future for a few reasons:
- I would rather provide all the other vanilla stuff that I'd missing
- I dont have the most knowledge about how it works, especially on Java
- Bedrock Ray Tracing/PBR related stuff I'd super broken and I don't want people thinking that the pack converter has created a broken pack when in reality the game just doesn't work properly 😅

If someone is interested in adding support, by all means give it a go! But it's not something I'll be doing in the foreseeable future. Apologies.

-Alien
