### ISSUE TITLE
java 1.19.4

### ISSUE THREAD

**Issue by frogglen** [TheAlienDoctor/minecraft-resource-pack-converter#8]
i am trying to convert a java package to bedrock, i put my unzipped java package in imputs and when i run the converter, it only converts like 2 or 3 files, am i doing something wrong or is there a bug?

**Comment by TheAlienDoctor** [comment]
Hey, not all files are supported at the moment. You can see #1 for a list of unsupported textures. If you post your log file from when you did the conversions (found inside the "logs" folder) I can double check everything looks ok, but its most likely that you are trying to convert files that are not yet supported.
Bear in mind this can only convert texture files, not any of the json ones :)

- Alien

**Comment by frogglen** [comment]
> 
I am trying to convert this package but I thought it would help me convert more than half but almost nothing converts.

https://www.dropbox.com/s/c71ms55w0iyvz98/kimucraft_resource_pack2.2.zip?dl=1

**Comment by TheAlienDoctor** [comment]
This pack is mostly made up of custom textures, which is why it is unable to convert them. It can only convert textures for items that are in the vanilla game.
