### ISSUE TITLE
Converting pack icon

### ISSUE THREAD

**Issue by LightslicerGP** [TheAlienDoctor/minecraft-resource-pack-converter#9]
atleast for bedrock to java, the pack icon doesn't convert over, it would b nice if it did

**Comment by TheAlienDoctor** [comment]
Are you using the latest version? This issue was fixed, unless something has changed.

**Comment by LightslicerGP** [comment]
> Are you using the latest version? This issue was fixed, unless something has changed.

I downloaded it yesterday, and the newest one, 1.2.1?

**Comment by TheAlienDoctor** [comment]
Yes this is the newest version, and I have converted multiple packs between multiple versions just now and not been able to replicate this issue. If you could link the pack you tried converting, that would be much appreciated. Until then, this issue will be closed.

- Alien

**Comment by LightslicerGP** [comment]
[Here's the pack,](https://www.mediafire.com/download/5tvskfjuskosyjv) I suspect it's because I have multiple files at the root directory (since I want to keep the older versions of the pack icon) so mabye that's why.
